version: '3'

services:
  test:
    image: typescript-library-test
    build:
      context: docker/test
    volumes:
      - ./:/src
    # https://stackoverflow.com/a/53975412/3145856
    # https://github.com/docker/compose/issues/5574
    security_opt:
      - seccomp:./docker/test/chrome.json
